version: "3.7"
services:
  backend:
    container_name: plataformasoporte-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    command: >
      sh -c "npx sequelize-cli db:migrate && 
             node app"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=laboratorio_bd
      - TZ=America/La_Paz
    volumes:
      - .:/app
      - /app/node_modules
      # Volumen para archivos persistentes
      #- /srv/docker-volumenes/plataformasoporte:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - plataformasoporte-network-dev

  postgres:
    image: postgres:15
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laboratorio_bd
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: America/La_Paz
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d laboratorio_bd"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - plataformasoporte-network-dev

networks:
  plataformasoporte-network-dev:
    driver: bridge
    
volumes:
  postgres_data:

